### ISSUE TITLE
缺少部分必要的样式

### ISSUE THREAD

**Issue by Lruihao** [pengzhanbo/caniuse-embed#1]
```css
.ciu-embed {
  iframe {
    display: block;
    width: 100%;
    border: none;
  }
}
```

不然 iframe 的宽度不回撑满 100%。

<img width="1172" alt="image" src="https://github.com/pengzhanbo/caniuse-embed/assets/33419593/5b477da2-e915-4f79-be74-028d16e467db">
